tokens:
  - chainName: alfajores
    standard: EvmHypCollateral
    decimals: 6
    symbol: USDC
    name: USDC
    addressOrDenom: "0x2351e45AF67d7C2C728D633F4A336d83b503ABCB"
    collateralAddressOrDenom: "0x2F25deB3848C207fc8E0c34035B3Ba7fC157602B"
    connections:
      - token: ethereum|rootstock|0xE71c1C60E004bD8be8d8DAF312828d7F9366d761
  - chainName: rootstock
    standard: EvmHypCollateral
    decimals: 6
    symbol: USDC
    name: USDC
    addressOrDenom: "0xE71c1C60E004bD8be8d8DAF312828d7F9366d761"
    collateralAddressOrDenom: "0x81532a7ab169efb8c3a0b6a173c8c4613a336eea"
    connections:
      - token: ethereum|alfajores|0x2351e45AF67d7C2C728D633F4A336d83b503ABCB
